
# handler paths are relative to the root serverless.yml file that this is being merged into
# they are also compiled by babel into a 'dist' folder at the root
list:
  handler: src/handlers/users/list.handler
  events:
    - http:
        path: users
        method: get
        authorizer:
          name: auth
          resultTtlInSeconds: 300
          identitySource: method.request.header.Authorization
          type: token
get:
  handler: src/handlers/users/get.handler
  events:
    - http:
        path: /users/{id}
        method: get
        authorizer:
          name: auth
          resultTtlInSeconds: 300
          identitySource: method.request.header.Authorization
          type: token
add:
  handler: src/handlers/users/add.handler
  events:
    - http:
        path: /users
        method: post
update:
  handler: src/handlers/users/update.handler
  events:
    - http:
        path: /users/{id}
        method: put
        authorizer:
          name: auth
          resultTtlInSeconds: 300
          identitySource: method.request.header.Authorization
          type: token
delete:
  handler: src/handlers/users/delete.handler
  events:
    - http:
        path: /users/{id}
        method: delete
        authorizer:
          name: auth
          resultTtlInSeconds: 300
          identitySource: method.request.header.Authorization
          type: token
auth:
  handler: src/handlers/auth/auth.handler
